<a href="https://colab.research.google.com/github/Fasiloc/Python_learn-repo/blob/main/Classes/Day_12_Numpy_class_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,2,3],[4,5,6]],np.int32)
type(x)



numpy.ndarray

In [ ]:
x.shape

(2, 3)

In [ ]:
x.ndim

2

In [ ]:
x.dtype

dtype('int32')

In [ ]:
x.size

6

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a=np.arange(15).reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
a.shape

(5, 3)

In [ ]:
a.ndim

2

In [ ]:
a.itemsize

8

In [ ]:
a.size

15

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a=np.array([1,2,'a','b'])
a.dtype

dtype('<U21')

In [ ]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0,3.0,num=5,endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0,3.0,num=5,retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [ ]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
(2**x)


array([ 1,  2,  4,  8, 16])

In [ ]:
y=np.arange(-1,1.1,0.5)
y

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [ ]:
np.abs(y)

array([1. , 0.5, 0. , 0.5, 1. ])

In [ ]:
z=np.arange(10)
np.sin(z)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,),dtype=int)

array([1, 1, 1, 1, 1])

In [ ]:
np.ones((2,1))

array([[1.],
       [1.]])

In [ ]:
s=(2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

In [ ]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((6,),dtype=int)

array([0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [ ]:
np.logspace(2.0,3.0,num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [ ]:
np.random.rand(3,2)

array([[0.66479171, 0.58964442],
       [0.61369796, 0.81750505],
       [0.69514121, 0.58938645]])

In [ ]:
print(np.random.rand(128))

[0.59141583 0.43030058 0.02444057 0.34485877 0.81534892 0.14393933
 0.78938112 0.29765196 0.97829634 0.54480979 0.10525672 0.31048785
 0.17949378 0.5515632  0.58974917 0.5627988  0.94997479 0.85514705
 0.08543988 0.58394337 0.73909819 0.74735225 0.26777193 0.92803629
 0.98397936 0.3886676  0.33669512 0.35625518 0.77985983 0.03278954
 0.64795126 0.99358618 0.99170325 0.95474152 0.89522425 0.46299047
 0.91381014 0.115328   0.27869277 0.39663562 0.34874445 0.35987919
 0.21584297 0.18910207 0.64798928 0.59291002 0.88565052 0.11096565
 0.57150888 0.35947157 0.20176863 0.78992087 0.12662551 0.02897091
 0.54221786 0.16606625 0.93980947 0.91490458 0.59325452 0.38526075
 0.00140746 0.12687275 0.51080193 0.83641673 0.33641719 0.98930705
 0.11718643 0.00343012 0.94635708 0.38113539 0.44067733 0.65576909
 0.09657523 0.46941275 0.4131987  0.91198907 0.50004102 0.227446
 0.63316822 0.80976503 0.20687891 0.67833279 0.10115267 0.00682432
 0.96558418 0.80779827 0.82954232 0.80644888 0.42269395 0.040898

In [ ]:
print(np.random.rand(128,5642,56))

[[[0.99565773 0.66650152 0.79813907 ... 0.91245576 0.10516551 0.19111233]
  [0.70312304 0.95279558 0.03768972 ... 0.00360225 0.29040623 0.81703107]
  [0.18202259 0.5992555  0.16754633 ... 0.40635948 0.38342805 0.1748121 ]
  ...
  [0.99025484 0.11935632 0.62098427 ... 0.23007235 0.43564972 0.12033544]
  [0.98453279 0.48355394 0.80077302 ... 0.9902262  0.03527007 0.28337269]
  [0.57539168 0.78618203 0.22275025 ... 0.59023017 0.82848428 0.14512825]]

 [[0.62026019 0.04398987 0.10249535 ... 0.1622133  0.68809926 0.92971138]
  [0.0472605  0.20286125 0.9175531  ... 0.92311428 0.39420623 0.83035511]
  [0.36481151 0.66774471 0.56655602 ... 0.87315619 0.49914171 0.25330152]
  ...
  [0.98438943 0.22205959 0.28294752 ... 0.25898076 0.20975715 0.32159651]
  [0.93156926 0.85959399 0.65681838 ... 0.98751245 0.56551564 0.89080314]
  [0.92255271 0.32513996 0.93738231 ... 0.22535704 0.09545339 0.25463823]]

 [[0.79985687 0.76576025 0.1144627  ... 0.28083672 0.41368104 0.96978399]
  [0.57134436 0.543939

In [ ]:
np.random.randint(1000,2000,200)

array([1349, 1010, 1038, 1350, 1908, 1401, 1859, 1461, 1226, 1963, 1420,
       1578, 1520, 1092, 1763, 1076, 1097, 1734, 1575, 1332, 1729, 1258,
       1276, 1719, 1300, 1403, 1569, 1292, 1104, 1850, 1154, 1233, 1460,
       1901, 1661, 1638, 1211, 1642, 1216, 1817, 1010, 1856, 1969, 1124,
       1893, 1375, 1414, 1908, 1838, 1896, 1232, 1488, 1787, 1719, 1220,
       1975, 1472, 1549, 1922, 1542, 1707, 1087, 1186, 1583, 1597, 1870,
       1495, 1446, 1911, 1314, 1909, 1794, 1528, 1286, 1743, 1703, 1741,
       1489, 1553, 1846, 1963, 1255, 1489, 1778, 1317, 1159, 1441, 1919,
       1449, 1991, 1837, 1195, 1703, 1074, 1819, 1789, 1940, 1272, 1194,
       1410, 1467, 1623, 1750, 1265, 1652, 1562, 1055, 1292, 1777, 1207,
       1000, 1360, 1061, 1777, 1971, 1882, 1724, 1710, 1933, 1899, 1356,
       1679, 1381, 1164, 1019, 1028, 1612, 1731, 1298, 1518, 1376, 1826,
       1910, 1721, 1206, 1959, 1606, 1718, 1493, 1008, 1384, 1483, 1125,
       1412, 1823, 1601, 1989, 1349, 1952, 1241, 13