<a href="https://colab.research.google.com/github/Fasiloc/Python_learn-repo/blob/main/Classes/Day_12_Numpy_Practicals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Python program to demonstrate basic array characteristics
import numpy as np
x=np.array([[4,5,6],[7,5,6]])
print(type(x))
print('Array :',x)
print('Shape of the array :',x.shape)
print('Data type of the array :',x.dtype)
print('Size of the array :',x.size)
print('Diamension of the array :',x.ndim)
print('Item size of the array :',x.itemsize)


<class 'numpy.ndarray'>
Array : [[4 5 6]
 [7 5 6]]
Shape of the array : (2, 3)
Data type of the array : int64
Size of the array : 6
Diamension of the array : 2
Item size of the array : 8


In [ ]:
#Python program to demonstrate array creation techniques
import numpy as np
print('Array created using linspace() :\n\n',np.linspace(1.25,4.75,num=12),'\n')
print('Array created using arange() :\n\n')
print(np.arange(8))
print(np.arange(6.74))
print(np.arange(2.13,12.10))
print(np.arange(3,16,3),'\n')
print('Array created using ones() :\n')
print(np.ones(5))
print(np.ones(11,dtype=int),'\n')
print(np.ones((3,3)),'\n')
print(np.ones((2,4),dtype=int),'\n')
print('Array created using zeros() :\n')
print(np.zeros(7))
print(np.zeros(9,dtype=int),'\n')
print(np.zeros((3,2)),'\n')
print(np.zeros((3,5),dtype=int),'\n')
print('Array created using logspace() :\n')
print(np.logspace(1.25,5.7,num=7),'\n')
print('Array created using random function :\n')
print(np.random.rand(2,9))

Array created using linspace() :

 [1.25       1.56818182 1.88636364 2.20454545 2.52272727 2.84090909
 3.15909091 3.47727273 3.79545455 4.11363636 4.43181818 4.75      ] 

Array created using arange() :


[0 1 2 3 4 5 6 7]
[0. 1. 2. 3. 4. 5. 6.]
[ 2.13  3.13  4.13  5.13  6.13  7.13  8.13  9.13 10.13 11.13]
[ 3  6  9 12 15] 

Array created using ones() :

[1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[1 1 1 1]
 [1 1 1 1]] 

Array created using zeros() :

[0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0] 

[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]] 

Array created using logspace() :

[1.77827941e+01 9.80994713e+01 5.41169527e+02 2.98538262e+03
 1.64689787e+04 9.08517576e+04 5.01187234e+05] 

Array created using random function :

[[0.79063432 0.33403921 0.83681711 0.88984976 0.03980624 0.45949513
  0.2270139  0.60298553 0.92451811]
 [0.52596712 0.22566803 0.5404702  0.09410364 0.83587029 0.1448312
  0.97469252 0.72349616 0.11190749

In [ ]:
#Python program to demonstrate indexing in numpy
import numpy as np
x1=np.array([2,7,85,65,42,9,34,1,8])
x2=np.array([[2,6,47],[5,32,4]])
x3=np.array([[[2,4,8],[4,2,5]],[[36,5,75],[7,32,4]]])
'''1 diamentional indexing'''
print(x1[2])
print(x1[-3])
'''2 diamensioal idexing'''
print(x2[1,2])
print(x2[0,-1])
print(x2[1,-3])
print(x2[-1,-1])
'''3 diamensional indexing'''
print(x3[1,0,1])
print(x3[-2,1,-1])

85
34
4
47
5
4
5
5


In [ ]:
#Python program to demonstrate basic operations on single array
x


In [ ]:
#Python program to demonstrate unary operators in numpy


In [ ]:
#Python program to demonstrate binary operators in numpy
import numpy as np
print(np.bitwise_and(75,45))
print(np.bitwise_or(11,8))
print(np.bitwise_xor(23,21))
print(np.invert(np.array(13)))
print(np.left_shift(9))
print(np.right_shift(15))


9
11
2
-14


ValueError: ignored

In [ ]:
#Python program to demonstrate universal functions in numpy

In [ ]:
#Python program to demonstrate sorting in numpy

In [ ]:
#Python program to get unique values from list